name: Python Flask Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:

  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install linting tools
      run: |
        pip install flake8
        pip install pylint
    
    - name: Linting with flake8
      run: flake8 app/

    - name: Linting with pylint
      run: pylint app/

  unittest:
    needs: linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Run tests
      run: python -m unittest discover -s tests

  image:
    needs: [linting, unittest]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build . -t SDP/mini_iot_spd_project